// styles.ts
// Styles thematises (clair / sombre). Utiliser createStyles(theme) au lieu de styles.

import { StyleSheet } from 'react-native';
import { Theme } from './theme';

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
      justifyContent: 'center',
    },
    scrollContainer: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 20,
      paddingHorizontal: 16,
    },
    carteFormulaire: {
      backgroundColor: theme.card,
      borderRadius: 16,
      paddingVertical: 32,
      paddingHorizontal: 24,
      width: '100%',
      maxWidth: 520,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
    },
    sousTitre: {
      fontSize: 15,
      textAlign: 'center',
      color: theme.textSecondary,
      fontFamily: 'Georgia',
      marginBottom: 24,
    },
    label: {
      fontSize: 15,
      fontWeight: 'bold',
      color: theme.textSecondary,
      marginBottom: 8,
      marginTop: 4,
      marginHorizontal: 20,
    },
    input: {
      fontSize: 18,
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 8,
      borderWidth: 2,
      borderColor: theme.border,
      backgroundColor: theme.inputBackground,
      color: theme.text,
      marginBottom: 12,
      marginHorizontal: 20,
    },
    inputGris: {
      backgroundColor: theme.border,
      color: theme.textSecondary,
      opacity: 0.6,
    },
    boutonValider: {
      backgroundColor: theme.primary,
      paddingVertical: 16,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
      marginHorizontal: 20,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 5,
      elevation: 3,
    },
    boutonSuivant: {
      backgroundColor: '#16a34a',
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 4,
      marginBottom: 8,
      marginHorizontal: 20,
    },
    boutonRetour: {
      backgroundColor: 'transparent',
      paddingVertical: 8,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 2,
      marginHorizontal: 20,
    },
    texteBoutonRetour: {
      color: theme.textSecondary,
      fontSize: 14,
      fontWeight: '600',
    },
    boutonDesactive: {
      backgroundColor: theme.primaryDisabled,
      elevation: 0,
      shadowOpacity: 0,
    },
    texteBouton: {
      color: '#ffffff',
      fontSize: 20,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    messageSucces: {
      backgroundColor: theme.successBg,
      borderWidth: 2,
      borderColor: theme.successBorder,
      borderRadius: 10,
      padding: 16,
      marginTop: 16,
    },
    texteSucces: {
      color: theme.successText,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: 'bold',
    },
    messageErreur: {
      backgroundColor: theme.errorBg,
      borderWidth: 2,
      borderColor: theme.errorBorder,
      borderRadius: 10,
      padding: 16,
      marginTop: 16,
    },
    texteErreur: {
      color: theme.errorText,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: 'bold',
    },
    boutonRelancer: {
      backgroundColor: theme.warning,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
    },
    texteBoutonRelancer: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: 'bold',
    },
    boutonChangerPC: {
      backgroundColor: theme.primaryDark,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 16,
    },
    texteBoutonPC: {
      color: '#ffffff',
      fontSize: 15,
      fontWeight: 'bold',
    },
    // Header avec bouton rond
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 16,
    },
    titrePrincipal: {
      fontSize: 22,
      fontWeight: 'bold',
      color: theme.text,
      fontFamily: 'Georgia',
      flex: 1,
    },
    boutonRond: {
      width: 36,
      height: 36,
      borderRadius: 18,
      marginLeft: 12,
    },
    etapeLabel: {
      fontSize: 13,
      color: theme.textSecondary,
      textAlign: 'center',
      marginBottom: 16,
      fontFamily: 'monospace',
    },
    badge: {
      backgroundColor: theme.badge,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      minWidth: 28,
      alignItems: 'center',
    },
    badgeTexte: {
      color: theme.badgeText,
      fontSize: 13,
      fontWeight: 'bold',
    },
    // Radio buttons classe
    radioRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 16,
    },
    radioItem: {
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 8,
      borderWidth: 2,
      borderColor: theme.radioInactiveBorder,
      backgroundColor: theme.radioInactiveBg,
      marginRight: 6,
      marginBottom: 6,
    },
    radioItemActif: {
      borderColor: theme.radioActive,
      backgroundColor: theme.radioActive,
    },
    radioTexte: {
      color: theme.text,
      fontSize: 15,
      fontWeight: 'bold',
    },
    radioTexteActif: {
      color: '#ffffff',
    },
    // Historique
    historiqueSection: {
      marginTop: 24,
      width: '100%',
    },
    historiqueTitre: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 12,
    },
    historiqueVide: {
      color: theme.textSecondary,
      fontSize: 14,
      fontStyle: 'italic',
      textAlign: 'center',
      paddingVertical: 12,
    },
    historiqueItem: {
      backgroundColor: theme.historyItem,
      borderWidth: 1,
      borderColor: theme.historyItemBorder,
      borderRadius: 10,
      padding: 12,
      marginBottom: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    historiqueContenu: {
      flex: 1,
    },
    historiqueTexte: {
      color: theme.text,
      fontSize: 15,
      fontWeight: 'bold',
    },
    historiqueMeta: {
      color: theme.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    historiqueStatut: {
      fontSize: 11,
      fontWeight: 'bold',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 6,
      overflow: 'hidden',
      marginLeft: 8,
    },
    historiqueStatutEnvoye: {
      backgroundColor: theme.successBorder,
      color: '#fff',
    },
    historiqueStatutAttente: {
      backgroundColor: theme.badge,
      color: theme.badgeText,
    },
    historiqueStatutErreur: {
      backgroundColor: theme.errorBorder,
      color: '#fff',
    },
    historiqueBouton: {
      backgroundColor: theme.primary,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 6,
      marginLeft: 8,
    },
    historiqueBoutonTexte: {
      color: '#fff',
      fontSize: 12,
      fontWeight: 'bold',
    },
    // Modal configuration IP
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.modalOverlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalContenu: {
      backgroundColor: theme.modalCard,
      borderRadius: 16,
      padding: 24,
      width: '100%',
      maxWidth: 500,
      maxHeight: '80%',
    },
    modalTitre: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 16,
      textAlign: 'center',
    },
    modalVide: {
      textAlign: 'center',
      color: theme.textSecondary,
      fontSize: 14,
      lineHeight: 22,
      marginVertical: 20,
    },
    modalItem: {
      padding: 14,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: theme.border,
      marginBottom: 8,
    },
    modalItemActif: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryDark,
    },
    modalItemNom: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.text,
    },
    modalItemAddr: {
      fontSize: 12,
      color: theme.textSecondary,
      fontFamily: 'monospace',
      marginTop: 2,
    },
    boutonFermer: {
      backgroundColor: theme.border,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      marginTop: 12,
    },
    texteBoutonFermer: {
      color: theme.text,
      fontSize: 15,
      fontWeight: 'bold',
    },
    // Bouton flottant debug
    boutonDebug: {
      position: 'absolute',
      bottom: 20,
      right: 20,
      backgroundColor: '#1a1a2e',
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      borderWidth: 2,
      borderColor: '#e94560',
    },
    texteBoutonDebug: {
      color: '#e94560',
      fontSize: 11,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    boutonDebugHaut: {
      bottom: 260,
    },
    consolePanel: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 240,
      backgroundColor: '#1a1a2e',
      borderTopWidth: 2,
      borderTopColor: '#e94560',
    },
    // Barre de connexion discrète
    barreConnexion: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 20,
      marginBottom: 16,
      alignSelf: 'center',
    },
    dotConnexion: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginRight: 6,
    },
    texteConnexion: {
      fontSize: 12,
      fontWeight: '600',
    },
    // Panneau debug secret
    debugPanel: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: '#1a1a2e',
      borderTopWidth: 2,
      borderTopColor: '#e94560',
      paddingBottom: 20,
    },
    debugHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: '#16162a',
      borderBottomWidth: 1,
      borderBottomColor: '#2d2d44',
    },
    debugTitre: {
      color: '#e94560',
      fontSize: 12,
      fontWeight: 'bold',
      fontFamily: 'monospace',
    },
    debugFermer: {
      color: '#94a3b8',
      fontSize: 14,
      fontWeight: 'bold',
    },
    debugContenu: {
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    debugLigne: {
      color: '#94a3b8',
      fontSize: 11,
      fontFamily: 'monospace',
      marginBottom: 4,
    },
    // --- Settings ---
    settingsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 16,
    },
    settingsTitre: {
      fontSize: 22,
      fontWeight: 'bold',
      color: theme.text,
      fontFamily: 'Georgia',
    },
    settingsBoutonFermer: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    settingsTexteFermer: {
      color: theme.text,
      fontSize: 16,
      fontWeight: 'bold',
    },
    settingsScroll: {
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    settingsBouton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
      paddingVertical: 14,
      paddingHorizontal: 16,
      marginBottom: 12,
    },
    settingsBoutonTexte: {
      color: theme.text,
      fontSize: 15,
      fontWeight: '600',
    },
    settingsBadge: {
      backgroundColor: '#dc2626',
      borderRadius: 10,
      minWidth: 22,
      height: 22,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 6,
      marginLeft: 8,
    },
    settingsBadgeTexte: {
      color: '#fff',
      fontSize: 12,
      fontWeight: 'bold',
    },
    settingsResultat: {
      fontSize: 14,
      fontWeight: 'bold',
      textAlign: 'center',
      marginBottom: 12,
    },
    settingsHistorique: {
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
      marginTop: 12,
      maxHeight: 300,
    },
    settingsHistoriqueTitre: {
      fontSize: 14,
      fontWeight: 'bold',
      color: theme.text,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 8,
    },
    settingsHistoriqueScroll: {
      flex: 1,
    },
    settingsHistoriqueVide: {
      color: theme.textSecondary,
      fontSize: 13,
      fontStyle: 'italic',
      textAlign: 'center',
      paddingVertical: 16,
    },
    settingsHistoriqueItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    settingsHistoriqueNom: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '600',
      flex: 1,
    },
    settingsHistoriqueHeure: {
      color: theme.textSecondary,
      fontSize: 12,
      marginLeft: 8,
    },
    settingsVersion: {
      color: theme.textSecondary,
      fontSize: 12,
      textAlign: 'center',
      marginTop: 20,
    },
    // Console overlay
    consoleOverlay: {
      backgroundColor: '#1a1a2e',
      borderRadius: 10,
      marginBottom: 12,
      overflow: 'hidden',
    },
    consoleHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: '#16162a',
    },
    consoleTitre: {
      color: '#94a3b8',
      fontSize: 12,
      fontWeight: 'bold',
      fontFamily: 'monospace',
    },
    consoleEffacer: {
      color: '#f5a623',
      fontSize: 12,
      fontWeight: 'bold',
    },
    consoleFermer: {
      color: '#94a3b8',
      fontSize: 14,
      fontWeight: 'bold',
    },
    consoleScroll: {
      maxHeight: 200,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    consoleVide: {
      color: '#475569',
      fontSize: 12,
      fontFamily: 'monospace',
      textAlign: 'center',
      paddingVertical: 16,
    },
    consoleLigne: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 3,
      gap: 6,
    },
    consoleBadge: {
      fontSize: 9,
      fontWeight: 'bold',
      color: '#fff',
      paddingHorizontal: 4,
      paddingVertical: 1,
      borderRadius: 3,
      overflow: 'hidden',
      minWidth: 40,
      textAlign: 'center',
    },
    consoleSource: {
      color: '#3b82f6',
      fontSize: 10,
      fontWeight: '600',
      fontFamily: 'monospace',
    },
    consoleMessage: {
      color: '#94a3b8',
      fontSize: 10,
      fontFamily: 'monospace',
      flex: 1,
    },
  });
