// styles.ts
// Styles thematises (clair / sombre). Utiliser createStyles(theme) au lieu de styles.

import { StyleSheet } from 'react-native';
import { Theme } from './theme';

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollContainer: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 20,
      paddingHorizontal: 16,
    },
    carteFormulaire: {
      backgroundColor: theme.card,
      borderRadius: 16,
      paddingVertical: 32,
      paddingHorizontal: 24,
      width: '100%',
      maxWidth: 520,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
    },
    titrePrincipal: {
      fontSize: 26,
      fontWeight: 'bold',
      textAlign: 'center',
      color: theme.text,
      fontFamily: 'Georgia',
      marginBottom: 6,
    },
    sousTitre: {
      fontSize: 15,
      textAlign: 'center',
      color: theme.textSecondary,
      fontFamily: 'Georgia',
      marginBottom: 24,
    },
    label: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 6,
      marginTop: 4,
    },
    input: {
      fontSize: 18,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      borderWidth: 2,
      borderColor: theme.border,
      backgroundColor: theme.inputBackground,
      color: theme.text,
      marginBottom: 16,
    },
    boutonValider: {
      backgroundColor: theme.primary,
      paddingVertical: 16,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 5,
      elevation: 3,
    },
    boutonDesactive: {
      backgroundColor: theme.primaryDisabled,
      elevation: 0,
      shadowOpacity: 0,
    },
    texteBouton: {
      color: '#ffffff',
      fontSize: 20,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    messageSucces: {
      backgroundColor: theme.successBg,
      borderWidth: 2,
      borderColor: theme.successBorder,
      borderRadius: 10,
      padding: 16,
      marginTop: 16,
    },
    texteSucces: {
      color: theme.successText,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: 'bold',
    },
    messageErreur: {
      backgroundColor: theme.errorBg,
      borderWidth: 2,
      borderColor: theme.errorBorder,
      borderRadius: 10,
      padding: 16,
      marginTop: 16,
    },
    texteErreur: {
      color: theme.errorText,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: 'bold',
    },
    boutonRelancer: {
      backgroundColor: theme.warning,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
    },
    texteBoutonRelancer: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: 'bold',
    },
    boutonChangerPC: {
      backgroundColor: theme.primaryDark,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 16,
    },
    texteBoutonPC: {
      color: '#ffffff',
      fontSize: 15,
      fontWeight: 'bold',
    },
    // Header avec gear + badge file d'attente
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
      gap: 8,
    },
    headerGear: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.primaryDark,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerGearTexte: {
      color: '#ffffff',
      fontSize: 18,
    },
    badge: {
      backgroundColor: theme.badge,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      minWidth: 28,
      alignItems: 'center',
    },
    badgeTexte: {
      color: theme.badgeText,
      fontSize: 13,
      fontWeight: 'bold',
    },
    // Radio buttons classe
    radioRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 16,
    },
    radioItem: {
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 8,
      borderWidth: 2,
      borderColor: theme.radioInactiveBorder,
      backgroundColor: theme.radioInactiveBg,
      marginRight: 6,
      marginBottom: 6,
    },
    radioItemActif: {
      borderColor: theme.radioActive,
      backgroundColor: theme.radioActive,
    },
    radioTexte: {
      color: theme.text,
      fontSize: 15,
      fontWeight: 'bold',
    },
    radioTexteActif: {
      color: '#ffffff',
    },
    // Historique
    historiqueSection: {
      marginTop: 24,
      width: '100%',
    },
    historiqueTitre: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 12,
    },
    historiqueVide: {
      color: theme.textSecondary,
      fontSize: 14,
      fontStyle: 'italic',
      textAlign: 'center',
      paddingVertical: 12,
    },
    historiqueItem: {
      backgroundColor: theme.historyItem,
      borderWidth: 1,
      borderColor: theme.historyItemBorder,
      borderRadius: 10,
      padding: 12,
      marginBottom: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    historiqueContenu: {
      flex: 1,
    },
    historiqueTexte: {
      color: theme.text,
      fontSize: 15,
      fontWeight: 'bold',
    },
    historiqueMeta: {
      color: theme.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    historiqueStatut: {
      fontSize: 11,
      fontWeight: 'bold',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 6,
      overflow: 'hidden',
      marginLeft: 8,
    },
    historiqueStatutEnvoye: {
      backgroundColor: theme.successBorder,
      color: '#fff',
    },
    historiqueStatutAttente: {
      backgroundColor: theme.badge,
      color: theme.badgeText,
    },
    historiqueStatutErreur: {
      backgroundColor: theme.errorBorder,
      color: '#fff',
    },
    historiqueBouton: {
      backgroundColor: theme.primary,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 6,
      marginLeft: 8,
    },
    historiqueBoutonTexte: {
      color: '#fff',
      fontSize: 12,
      fontWeight: 'bold',
    },
    // Modal configuration IP
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.modalOverlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalContenu: {
      backgroundColor: theme.modalCard,
      borderRadius: 16,
      padding: 24,
      width: '100%',
      maxWidth: 500,
      maxHeight: '80%',
    },
    modalTitre: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.text,
      marginBottom: 16,
      textAlign: 'center',
    },
    modalVide: {
      textAlign: 'center',
      color: theme.textSecondary,
      fontSize: 14,
      lineHeight: 22,
      marginVertical: 20,
    },
    modalItem: {
      padding: 14,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: theme.border,
      marginBottom: 8,
    },
    modalItemActif: {
      borderColor: theme.primary,
      backgroundColor: theme.primaryDark,
    },
    modalItemNom: {
      fontSize: 16,
      fontWeight: 'bold',
      color: theme.text,
    },
    modalItemAddr: {
      fontSize: 12,
      color: theme.textSecondary,
      fontFamily: 'monospace',
      marginTop: 2,
    },
    boutonFermer: {
      backgroundColor: theme.border,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      marginTop: 12,
    },
    texteBoutonFermer: {
      color: theme.text,
      fontSize: 15,
      fontWeight: 'bold',
    },
    // Bouton flottant debug
    boutonDebug: {
      position: 'absolute',
      bottom: 20,
      right: 20,
      backgroundColor: '#1a1a2e',
      width: 52,
      height: 52,
      borderRadius: 26,
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 6,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      borderWidth: 2,
      borderColor: '#e94560',
    },
    texteBoutonDebug: {
      color: '#e94560',
      fontSize: 11,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    boutonDebugHaut: {
      bottom: 260,
    },
    consolePanel: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 240,
      backgroundColor: '#1a1a2e',
      borderTopWidth: 2,
      borderTopColor: '#e94560',
    },
    consoleHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: '#16162a',
      borderBottomWidth: 1,
      borderBottomColor: '#2d2d44',
    },
    consoleTitre: {
      color: '#94a3b8',
      fontSize: 11,
      fontWeight: 'bold',
      fontFamily: 'monospace',
    },
    consoleEffacer: {
      color: '#e94560',
      fontSize: 11,
      fontWeight: 'bold',
    },
    consoleScroll: {
      flex: 1,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    consoleVide: {
      color: '#475569',
      fontSize: 11,
      fontFamily: 'monospace',
      textAlign: 'center',
      marginTop: 20,
    },
  });
